Repository GonzaloEBaez/vetsoft, pull requests merged in 2024-06, with the labels that each got.

#12 Feature/proveedor agregar direccion
  app/migrations/0011_merge_0009_provider_address_0010_alter_pet_birthday.py
  app/migrations/0012_alter_provider_address.py
  app/models.py
  app/templates/providers/form.html
  app/tests_integration.py
  app/tests_unit.py
  app/views.py
  functional_tests/tests.py
Labels: enhancement

#13 Feature/medicina-validar-dosis
  app/migrations/0011_merge_20240602_1712.py
  app/models.py
  app/templates/medicines/form.html
  app/tests_integration.py
  app/tests_unit.py
  app/views.py
  functional_tests/tests.py
Labels: bug, enhancement

#14 Feature/mascota validar nacimiento
  app/templates/pets/form.html
  app/views.py
Labels: bug

#15 Add peso mascota
  app/migrations/0011_merge_20240602_1740.py
  app/migrations/0012_alter_pet_weight.py
  app/models.py
  app/templates/pets/form.html
  app/tests_integration.py
  app/tests_unit.py
  functional_tests/tests.py
Labels: bug

#16 Revert "Add peso mascota"
  app/migrations/0011_merge_20240602_1740.py
  app/migrations/0012_alter_pet_weight.py
  app/models.py
  app/templates/pets/form.html
  app/tests_integration.py
  app/tests_unit.py
  functional_tests/tests.py
Labels: bug

#17 Corrección del Pull Request Revert #16
  functional_tests/tests.py
Labels: bug

#18 Feature/veterinario validar precio
  app/migrations/0012_alter_product_price.py
  app/models.py
  app/templates/products/form.html
  app/templates/veterinaries/form.html
  app/tests_unit.py
  app/views.py
Labels: bug

#20 Correccion de validacion del campo nacimiento en Mascota
  app/models.py
  app/templates/pets/form.html
Labels: bug

#24 Refactor/D103
  .ruff.toml
  app/context_processors.py
  app/models.py
  app/tests_unit.py
  app/views.py
Labels: documentation

#34 Refactor/cliente validar telefono
  app/migrations/0015_merge_20240605_1156.py
  app/migrations/0021_merge_20240605_1308.py
  app/models.py
  app/templates/clients/form.html
  app/tests_integration.py
  app/tests_unit.py
  functional_tests/tests.py
Labels: refactor

#35 Refactor/D103
  app/models.py
Labels: refactor

#36 Revert "Refactor/D103"
  app/models.py
Labels: bug

#28 Refactor/campos telefono solo numeros
  app/models.py
  app/templates/clients/form.html
  app/tests_integration.py
  app/tests_unit.py
Labels: enhancement, refactor

#37 Fix/Deploy
  Dockerfile
Labels: bug

#38 Bugfix/deploy continuo
  .dockerignore
  Dockerfile
  vetsoft/settings.py
Labels: bug

#40 arreglo docker file
  Dockerfile
Labels: bug

#42 Agrego test e2e para validar nombre de cliente.
  functional_tests/tests.py
Labels: enhancement

#41 Fix/cliente-ciudad-tests
  app/tests_integration.py
  app/tests_unit.py
  functional_tests/tests.py
Labels: bug

#44 Add/test validar telefono
  app/tests_unit.py
  functional_tests/tests.py
Labels: enhancement

#45 Bugfix/validar campo numerico
  app/tests_unit.py
  functional_tests/tests.py
Labels: enhancement
